repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
        args: ["--ignore=E501,E265,E302,E305"]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3

